# Generated by Django 4.0.3 on 2022-04-03 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
